### ISSUE TITLE
Не работает поиск (Ошибка поиска адреса).

### ISSUE THREAD

**Issue by zirsy** [openstreetmap-ru/OpenStreetMap.ru#260]
Не работает поиск адреса. Сначала появляется ошибка:*\* "Произошла ошибка #1: query failed: connection to localhost;3312 failed ([Errno 61] Connection refused)"**. Потом она исчезает и появляется: **"Ошибка #2: error undefined"**. На карте ничего не происходит.

**Comment by ErshKUS** [comment]
поисковый движок переодически отваливается с ошибкой
> [Thu Apr 14 18:26:24.607 2016] [29625] WARNING: failed to receive client request body (client=127.0.0.1, exp=280)
> [Thu Apr 14 18:26:47.195 2016] [29625] WARNING: failed to receive client request body (client=127.0.0.1, exp=280)
> [Thu Apr 14 18:38:54.612 2016] [29624] Child process 29625 has been killed with kill or sigterm (9). Watchdog finishes also. Good bye!

пока ничего полезного не нагуглил

**Comment by toy-php** [comment]
Поднимаю вопрос, ошибка еще существует.

request:
GET http://openstreetmap.ru/api/search?q=москва
response:
{"search": "москва", "error": "query failed: connection to localhost;3312 failed ([Errno 61] Connection refused)", "ver": "0.7", "find": false, "in": {"cnt": 12, "lon": 0.0, "outCallback": "", "st": "all", "q": "москва", "lat": 0.0, "nolimit": false, "asis": true}}
